import type { TeamMember, TeamInvite } from '../domain/team/contracts';

const AVATAR_URLS = [
  'https://images.unsplash.com/photo-1655249493799-9cee4fe983bb?w=80&h=80&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1672685667592-0392f458f46f?w=80&h=80&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1641808895769-29e63aa2f066?w=80&h=80&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1762708550141-2688121b9ebd?w=80&h=80&fit=crop&crop=face',
  'https://images.unsplash.com/photo-1753162660224-7852bd04f827?w=80&h=80&fit=crop&crop=face',
];

export const TEAM_DEMO_MEMBERS: TeamMember[] = [
  {
    id: 'user-ana',
    name: 'Ana Silva',
    email: 'ana.silva@agencia.com',
    image: AVATAR_URLS[0],
    role: 'manager',
    jobTitle: 'Gestora de Projetos',
    department: 'Gestão',
    color: '#ff5623',
    status: 'active',
    boardIds: ['board-my-workspace', 'board-board-de-teste'],
    joinedAt: '2024-01-10T09:00:00Z',
    phone: '+55 11 99999-0001',
    location: 'São Paulo, SP',
  },
  {
    id: 'user-carlos',
    name: 'Carlos Lima',
    email: 'carlos.lima@agencia.com',
    image: AVATAR_URLS[1],
    role: 'collaborator',
    jobTitle: 'Desenvolvedor Frontend',
    department: 'Tecnologia',
    color: '#987dfe',
    status: 'active',
    boardIds: ['board-my-workspace'],
    joinedAt: '2024-02-15T09:00:00Z',
    phone: '+55 11 99999-0002',
    location: 'São Paulo, SP',
    permissions: {
      view_operational_reports: true, // override individual: tem acesso a relatórios op
    },
  },
  {
    id: 'user-mariana',
    name: 'Mariana Costa',
    email: 'mariana.costa@agencia.com',
    image: AVATAR_URLS[2],
    role: 'collaborator',
    jobTitle: 'Designer UI/UX',
    department: 'Criação',
    color: '#019364',
    status: 'active',
    boardIds: ['board-my-workspace', 'board-board-de-teste'],
    joinedAt: '2024-03-01T09:00:00Z',
    location: 'Curitiba, PR',
  },
  {
    id: 'user-rafael',
    name: 'Rafael Santos',
    email: 'rafael.santos@agencia.com',
    image: AVATAR_URLS[3],
    role: 'collaborator',
    jobTitle: 'Desenvolvedor Backend',
    department: 'Tecnologia',
    color: '#3b82f6',
    status: 'active',
    boardIds: ['board-my-workspace'],
    joinedAt: '2024-04-05T09:00:00Z',
  },
  {
    id: 'user-julia',
    name: 'Julia Ferreira',
    email: 'julia.ferreira@agencia.com',
    image: AVATAR_URLS[4],
    role: 'collaborator',
    jobTitle: 'QA Engineer',
    department: 'Qualidade',
    color: '#f32c2c',
    status: 'inactive',
    boardIds: [],
    joinedAt: '2024-05-20T09:00:00Z',
  },
  // Clientes
  {
    id: 'user-luiza-arcadia',
    name: 'Luiza Arcadia',
    email: 'luiza@arcadia.com',
    image: AVATAR_URLS[0],
    role: 'client',
    jobTitle: 'Diretora de Marketing',
    department: 'Marketing',
    color: '#feba31',
    status: 'active',
    clientId: 'client-arcadia',
    boardIds: ['board-my-workspace'],
    joinedAt: '2024-06-01T09:00:00Z',
  },
  {
    id: 'user-pedro-arcadia',
    name: 'Pedro Arcadia',
    email: 'pedro@arcadia.com',
    image: AVATAR_URLS[3],
    role: 'client',
    jobTitle: 'Coordenador de Produto',
    department: 'Produto',
    color: '#feba31',
    status: 'active',
    clientId: 'client-arcadia',
    boardIds: ['board-my-workspace'],
    joinedAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'user-bruna-ifood',
    name: 'Bruna iFood',
    email: 'bruna@ifood.com.br',
    image: AVATAR_URLS[2],
    role: 'client',
    jobTitle: 'Analista de Growth',
    department: 'Growth',
    color: '#ff5623',
    status: 'active',
    clientId: 'client-ifood',
    boardIds: [],
    joinedAt: '2024-09-15T09:00:00Z',
  },
];

export const TEAM_DEMO_INVITES: TeamInvite[] = [
  {
    id: 'invite-001',
    email: 'novo.designer@agencia.com',
    role: 'collaborator',
    invitedBy: 'user-ana',
    token: 'abc123xyz456',
    status: 'pending',
    expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    boardIds: ['board-my-workspace'],
  },
  {
    id: 'invite-002',
    email: 'cliente@empresa-nova.com',
    role: 'client',
    invitedBy: 'user-ana',
    token: 'def789uvw012',
    status: 'pending',
    expiresAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    boardIds: [],
    clientId: 'client-weplanner',
  },
];
